<?php

namespace Database\Seeders;

use App\Models\Cliente;
use App\Models\Empresa;
use App\Models\Sucursal;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientesSeeder extends Seeder
{
    public function run()
    {
        // Obtener la primera empresa y sucursal
        $empresa = Empresa::first();
        $sucursal = Sucursal::where('empresa_id', $empresa->id)->first();
        
        if (!$empresa || !$sucursal) {
            $this->command->error('No se encontró empresa o sucursal. Por favor, ejecute EmpresaSeeder y SucursalSeeder primero.');
            return;
        }

        $clientes = [
            [
                'nombre' => 'Carlos',
                'apellido' => 'González Pérez',
                'documento' => '1234567',
                'tipo_documento' => 'CI',
                'email' => 'carlos.gonzalez@email.com',
                'telefono' => '0981-234567',
                'telefono_alternativo' => '0981-765432',
                'direccion' => 'Av. Principal 1234',
                'ciudad' => 'Asunción',
                'estado_region' => 'Capital',
                'activo' => true,
                'ocupacion' => 'Empleado Privado',
                'empresa_trabajo' => 'Tech Solutions S.A.',
                'ingreso_mensual_estimado' => 3500000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'María',
                'apellido' => 'Rodríguez Martínez',
                'documento' => '2345678',
                'tipo_documento' => 'CI',
                'email' => 'maria.rodriguez@email.com',
                'telefono' => '0982-345678',
                'telefono_alternativo' => null,
                'direccion' => 'Calle Central 567',
                'ciudad' => 'San Lorenzo',
                'estado_region' => 'Central',
                'activo' => true,
                'ocupacion' => 'Profesora',
                'empresa_trabajo' => 'Colegio Nacional',
                'ingreso_mensual_estimado' => 2800000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Juan',
                'apellido' => 'López Fernández',
                'documento' => '3456789',
                'tipo_documento' => 'CI',
                'email' => 'juan.lopez@email.com',
                'telefono' => '0983-456789',
                'telefono_alternativo' => '0983-987654',
                'direccion' => 'Barrio Norte, Casa 45',
                'ciudad' => 'Luque',
                'estado_region' => 'Central',
                'activo' => true,
                'ocupacion' => 'Comerciante',
                'empresa_trabajo' => 'López Comercial',
                'ingreso_mensual_estimado' => 4200000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Ana',
                'apellido' => 'Martínez Silva',
                'documento' => '4567890',
                'tipo_documento' => 'CI',
                'email' => 'ana.martinez@email.com',
                'telefono' => '0984-567890',
                'telefono_alternativo' => null,
                'direccion' => 'Av. Costanera 890',
                'ciudad' => 'Encarnación',
                'estado_region' => 'Itapúa',
                'activo' => true,
                'ocupacion' => 'Enfermera',
                'empresa_trabajo' => 'Hospital Regional',
                'ingreso_mensual_estimado' => 3100000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Pedro',
                'apellido' => 'Giménez Ramírez',
                'documento' => '5678901',
                'tipo_documento' => 'CI',
                'email' => 'pedro.gimenez@email.com',
                'telefono' => '0985-678901',
                'telefono_alternativo' => '0985-109876',
                'direccion' => 'Calle 14, Nº 234',
                'ciudad' => 'Capiatá',
                'estado_region' => 'Central',
                'activo' => true,
                'ocupacion' => 'Ingeniero',
                'empresa_trabajo' => 'Constructora ABC',
                'ingreso_mensual_estimado' => 5200000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Laura',
                'apellido' => 'Sánchez Acosta',
                'documento' => '6789012',
                'tipo_documento' => 'CI',
                'email' => 'laura.sanchez@email.com',
                'telefono' => '0986-789012',
                'telefono_alternativo' => null,
                'direccion' => 'Shopping del Sol, Local 12',
                'ciudad' => 'Asunción',
                'estado_region' => 'Capital',
                'activo' => true,
                'ocupacion' => 'Contadora',
                'empresa_trabajo' => 'Estudio Contable',
                'ingreso_mensual_estimado' => 3800000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Diego',
                'apellido' => 'Molina Ríos',
                'documento' => '7890123',
                'tipo_documento' => 'CI',
                'email' => 'diego.molina@email.com',
                'telefono' => '0987-890123',
                'telefono_alternativo' => '0987-321098',
                'direccion' => 'Ruta PY02, Km 45',
                'ciudad' => 'Caaguazú',
                'estado_region' => 'Caaguazú',
                'activo' => true,
                'ocupacion' => 'Agricultor',
                'empresa_trabajo' => 'Agricultura Molina',
                'ingreso_mensual_estimado' => 4500000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Silvia',
                'apellido' => 'Cardozo Pereira',
                'documento' => '8901234',
                'tipo_documento' => 'CI',
                'email' => 'silvia.cardozo@email.com',
                'telefono' => '0988-901234',
                'telefono_alternativo' => null,
                'direccion' => 'Barrio San Jorge, Mz A, Casa 5',
                'ciudad' => 'Fernando de la Mora',
                'estado_region' => 'Central',
                'activo' => true,
                'ocupacion' => 'Abogada',
                'empresa_trabajo' => 'Estudio Jurídico',
                'ingreso_mensual_estimado' => 4800000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Roberto',
                'apellido' => 'Duarte Benítez',
                'documento' => '9012345',
                'tipo_documento' => 'CI',
                'email' => 'roberto.duarte@email.com',
                'telefono' => '0989-012345',
                'telefono_alternativo' => '0989-543210',
                'direccion' => 'Av. Gral. Santos 123',
                'ciudad' => 'Concepción',
                'estado_region' => 'Concepción',
                'activo' => true,
                'ocupacion' => 'Mecánico',
                'empresa_trabajo' => 'Taller Mecánico Duarte',
                'ingreso_mensual_estimado' => 3200000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Carmen',
                'apellido' => 'Aguilar Ortega',
                'documento' => '0123456',
                'tipo_documento' => 'CI',
                'email' => 'carmen.aguilar@email.com',
                'telefono' => '0990-123456',
                'telefono_alternativo' => null,
                'direccion' => 'Calle Iturbe 789',
                'ciudad' => 'Villarrica',
                'estado_region' => 'Guairá',
                'activo' => true,
                'ocupacion' => 'Estilista',
                'empresa_trabajo' => 'Salón de Belleza Carmen',
                'ingreso_mensual_estimado' => 2700000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            // Clientes adicionales para completar 15
            [
                'nombre' => 'Miguel',
                'apellido' => 'Ramírez Cabrera',
                'documento' => '1122334',
                'tipo_documento' => 'CI',
                'email' => 'miguel.ramirez@email.com',
                'telefono' => '0991-234567',
                'telefono_alternativo' => '0991-765432',
                'direccion' => 'Barrio Obrero, Casa 89',
                'ciudad' => 'San Pedro',
                'estado_region' => 'San Pedro',
                'activo' => true,
                'ocupacion' => 'Chofer',
                'empresa_trabajo' => 'Transportes Ramírez',
                'ingreso_mensual_estimado' => 2900000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Patricia',
                'apellido' => 'Benítez González',
                'documento' => '2233445',
                'tipo_documento' => 'CI',
                'email' => 'patricia.benitez@email.com',
                'telefono' => '0992-345678',
                'telefono_alternativo' => null,
                'direccion' => 'Av. Mariscal López 456',
                'ciudad' => 'Asunción',
                'estado_region' => 'Capital',
                'activo' => true,
                'ocupacion' => 'Vendedora',
                'empresa_trabajo' => 'Tiendas Benítez',
                'ingreso_mensual_estimado' => 2500000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Luis',
                'apellido' => 'Mendoza Silva',
                'documento' => '3344556',
                'tipo_documento' => 'CI',
                'email' => 'luis.mendoza@email.com',
                'telefono' => '0993-456789',
                'telefono_alternativo' => '0993-987654',
                'direccion' => 'Ruta PY07, Km 23',
                'ciudad' => 'Coronel Oviedo',
                'estado_region' => 'Caaguazú',
                'activo' => true,
                'ocupacion' => 'Electricista',
                'empresa_trabajo' => 'Electricidad Mendoza',
                'ingreso_mensual_estimado' => 3300000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Rosa',
                'apellido' => 'Fernández Ramírez',
                'documento' => '4455667',
                'tipo_documento' => 'CI',
                'email' => 'rosa.fernandez@email.com',
                'telefono' => '0994-567890',
                'telefono_alternativo' => null,
                'direccion' => 'Calle San Juan 234',
                'ciudad' => 'Ciudad del Este',
                'estado_region' => 'Alto Paraná',
                'activo' => true,
                'ocupacion' => 'Secretaria',
                'empresa_trabajo' => 'Importadora Fernández',
                'ingreso_mensual_estimado' => 2600000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
            [
                'nombre' => 'Alberto',
                'apellido' => 'Pereira Gómez',
                'documento' => '5566778',
                'tipo_documento' => 'CI',
                'email' => 'alberto.pereira@email.com',
                'telefono' => '0995-678901',
                'telefono_alternativo' => '0995-109876',
                'direccion' => 'Barrio Trinidad, Casa 67',
                'ciudad' => 'Paraguarí',
                'estado_region' => 'Paraguarí',
                'activo' => true,
                'ocupacion' => 'Panadero',
                'empresa_trabajo' => 'Panadería Pereira',
                'ingreso_mensual_estimado' => 2400000,
                'empresa_id' => $empresa->id,
                'sucursal_id' => $sucursal->id,
            ],
        ];

        $this->command->info('Creando ' . count($clientes) . ' clientes...');

        foreach ($clientes as $cliente) {
            try {
                Cliente::create($cliente);
            } catch (\Exception $e) {
                $this->command->error('Error al crear cliente: ' . $e->getMessage());
            }
        }

        $this->command->info('✓ Clientes creados exitosamente');
    }
}